main/urls.py
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'index', name='index'),
    url(r'^wall/$', 'wall', name='wall'),
    url(r'^live_search/$', 'live_search', name='live_search'),
    url(r'^box/leave/$', 'leave_box', name='leave_box'),
    url(r'^box/(?P<slug>[\w-]+)/$', 'box_detail', name='box_detail'),
)

third_party/django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

third_party/django_summernote/urls.py
from django.conf.urls import patterns, url
from django_summernote.views import editor, upload_attachment

urlpatterns = patterns(
    'django_summernote.views',
    url(r'^editor/(?P<id>.+)/$', editor,
        name='django_summernote-editor'),
    url(r'^upload_attachment/$', upload_attachment,
        name='django_summernote-upload_attachment'),
)

third_party/djangoappengine/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

urls.py
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import patterns, url, include
from django.views.generic.base import TemplateView, RedirectView
from main.views import cached_javascript_catalog

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from yawdadmin import admin_site
admin_site._registry.update(admin.site._registry)


js_info_dict = {
    'packages': ('main',),
}

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    url(r'^jsi18n/$', cached_javascript_catalog, js_info_dict, name='cached_javascript_catalog'),
    (r'^i18n/', include('django.conf.urls.i18n')),


    url(r'^admin/', include(admin_site.urls)),

    url('', include('adminoauthlogin.urls', namespace='adminoauthlogin')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/',}, name='auth_logout_next'),
    (r'^summernote/', include('django_summernote.urls')),

    (r'^favicon\.ico$', RedirectView.as_view(url='/static/global/favicon.ico')),
    (r'^robots\.txt$', TemplateView.as_view(template_name='main/robots.txt', content_type='text/plain')),
    (r'^sitemap\.xml$', TemplateView.as_view(template_name='main/sitemap.xml', content_type='application/xml')),

    url('', include('main.urls', namespace='main')),
    url('invitations/', include('invitations.urls', namespace='invitations')),
    url('', include('help.urls', namespace='help')),
)

third_party/yawdadmin/models.py
from django.db import models
from .fields import OptionNameField


class AppOption(models.Model):
    optionset_label = models.CharField(max_length=50)
    name = OptionNameField(max_length=50)
    value = models.TextField(null=True)
    lang_dependant = models.BooleanField(default=False)

    class Meta:
        unique_together = ('optionset_label', 'name')
        ordering = ['optionset_label', 'lang_dependant']

    def __unicode__(self):
        return u'%s.%s' % (self.optionset_label, self.name)

third_party/yawdadmin/forms.py
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.forms.formsets import TOTAL_FORM_COUNT
from django.forms.models import BaseInlineFormSet
from django.utils.translation import ungettext


class PopupInlineFormSet(BaseInlineFormSet):
    changed_objects = []
    deleted_objects = []
    new_objects = []

    def is_valid(self):
        """
        Do not validate any forms, no forms actually exist
        """
        return True

    def clean(self):
        """
        Clean should not validate forms.
        """
        pass

    def full_clean(self):
        """
        Do not check for form errors as it will force form validation.
        The clean() hook remains for possible use in subclasses.
        """
        self._errors = []
        self._non_form_errors = self.error_class()

        if not self.is_bound: # Stop further processing.
            return

        try:
            if (self.validate_max and
                self.total_form_count() - len(self.deleted_forms) > self.max_num) or \
                self.management_form.cleaned_data[TOTAL_FORM_COUNT] > self.absolute_max:
                raise ValidationError(ungettext(
                    "Please submit %d or fewer forms.",
                    "Please submit %d or fewer forms.", self.max_num) % self.max_num,
                    code='too_many_forms',
                )
            # Give self.clean() a chance to do cross-form validation.
            self.clean()
        except ValidationError as e:
            self._non_form_errors = self.error_class(e.messages)

    def get_add_url(self):
        return '%s?fk_name=%s&fk_id=%s' % (reverse('admin:%s_%s_add' % \
            (self.model._meta.app_label, self.model._meta.object_name.lower())),
                                  self.fk.name,
                                  self.instance.pk)

    def get_change_url(self, obj_id):
        return '%s?fk_name=%s' % (reverse('admin:%s_%s_change' % \
            (self.model._meta.app_label, self.model._meta.object_name.lower()),
            args=(obj_id,)),
                                  self.fk.name)

    def get_delete_url(self, obj_id):
        return reverse('admin:%s_%s_deleteit' % (self.model._meta.app_label,
                                                 self.model._meta.object_name.lower()),
                       args=(obj_id,))

    def get_reorder_url(self):
        return reverse('admin:%s_%s_inlinereorder' % (self.model._meta.app_label,
                                                 self.model._meta.object_name.lower()))

    def save(self, commit=True):
        """
        Override save_new to do nothing, as everything is handled by ajax requests.
        """
        return True

third_party/yawdadmin/views.py
import json
from oauth2client import xsrfutil
from oauth2client.file import Storage
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.utils.translation import ugettext as _
from django.views.generic import TemplateView, View, UpdateView
from conf import settings as ls


class AppOptionView(TemplateView):
    template_name = 'admin/options.html'
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.has_perm('yawdadmin.change_appoption'):
            raise PermissionDenied
        return super(AppOptionView, self).dispatch(request, *args, **kwargs)
    
    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instantiating the 
        form. Copied form the generic FormView class-based view
        """
        kwargs = {}
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data':self.request.POST, 
                'files':self.request.FILES, 
                })
        return kwargs

    def get_context_data(self, **kwargs):
        from yawdadmin import admin_site
        context = super(AppOptionView, self).get_context_data(**kwargs)
        context['optionset_admin'] = admin_site.get_optionset_admin(self.kwargs['optionset_label'])(**self.get_form_kwargs())
        context['title'] = '%s' % (unicode(context['optionset_admin'].verbose_name))
        return context
    
    def post(self, request, *args, **kwargs):
        """
        Validate the form and save the options upon success
        """
        context = self.get_context_data()
        if context['optionset_admin'].form.is_valid():
            context['optionset_admin'].save()
            messages.add_message(self.request, messages.SUCCESS, _('The options were succesfully saved.'))
        return self.render_to_response(context)
    
    def put(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class AnalyticsAuthView(View):
    """
    This view implements the oauth2 authentication callback.
    It stores the user credential to a file and redirects the user
    to the admin index page on success. 
    """
    permanent = False
    
    def get(self, request, *args, **kwargs):
        #check view
        valid_analytics_view(request)
        
        if not ('state' in request.REQUEST and xsrfutil.validate_token(settings.SECRET_KEY, request.REQUEST['state'], request.user)):
            return  HttpResponseBadRequest()
        
        credential = ls.ADMIN_GOOGLE_ANALYTICS_FLOW.step2_exchange(request.REQUEST) #@UndefinedVariable
        storage = Storage(ls.ADMIN_GOOGLE_ANALYTICS['token_file_name'])
        storage.put(credential)
        
        messages.add_message(self.request, messages.SUCCESS, _('The user was successfully connected.'))
        return HttpResponseRedirect(reverse('admin:analytics'))


class AnalyticsConfigView(TemplateView):
    """
    Admin view for the google analytics functionality. The view is 
    accessible through the top bar navigation.
    """
    template_name = 'admin/analytics.html'
    
    def get_context_data(self, **kwargs):
    
        #check view
        valid_analytics_view(self.request)
        #get original context data
        context = super(AnalyticsConfigView, self).get_context_data(**kwargs)
        #load the token file
        try:
            dat_file = open(ls.ADMIN_GOOGLE_ANALYTICS['token_file_name'], 'r')
            analytics = json.loads(dat_file.read())
            dat_file.close()
        except (IOError, ValueError):
            analytics = {}
        
        context['analytics_info'] = {
            'profile' : ls.ADMIN_GOOGLE_ANALYTICS['profile_id'],
            'interval' : ls.ADMIN_GOOGLE_ANALYTICS['interval'],
            'data' : analytics
        }
        
        return context


class AnalyticsConnectView(View):
    """
    Connect a new user to the Google Analytics API
    """
    def get(self, request, *args, **kwargs):
        
        #check view
        valid_analytics_view(request)
        try: 
            #Empty the token file 
            dat_file = open(ls.ADMIN_GOOGLE_ANALYTICS['token_file_name'], 'w+')
            dat_file.write('')
            dat_file.close()
        except:
            messages.add_message(self.request, messages.ERROR, _('The server does not have permissions to write to the token file. Please contact your system administrator.'))
            return HttpResponseRedirect(reverse('admin:analytics'))

        #Initialize flow
        ls.ADMIN_GOOGLE_ANALYTICS_FLOW.params['state'] = xsrfutil.generate_token(settings.SECRET_KEY, request.user) #@UndefinedVariable
        return HttpResponseRedirect(ls.ADMIN_GOOGLE_ANALYTICS_FLOW.step1_get_authorize_url()) #@UndefinedVariable


def valid_analytics_view(request):
    """
    Check if the user is superuser and analytics functionality is enabled. 
    """
    if not request.user.is_superuser:
            raise PermissionDenied
    
    if not ls.ADMIN_GOOGLE_ANALYTICS_FLOW:
        raise Http404


class MyAccountView(UpdateView):
    template_name = 'registration/my_account.html'
    form_class = ls.ADMIN_USER_MODELFORM
    
    def __init__(self, *args, **kwargs):
        super(MyAccountView, self).__init__(*args, **kwargs)
        self.success_url = reverse('admin:my-account')
        
    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS,
                             _('Your account has been updated successfuly.'))
        return super(MyAccountView, self).form_valid(form)
    
    def get_object(self):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super(MyAccountView, self).get_context_data(**kwargs)
        context['title'] = _('My account')
        return context

third_party/yawdadmin/templates/reversion-compare/compare.html
{% extends "admin/object_history.html" %}
{% load url from future %}
{% load i18n admin_urls %}

{% block extrastyle %}{{ block.super }}
<style type="text/css">
    /* minimal style for the diffs */
    del, ins {
        color: #000;
        text-decoration: none;
    }
    del { background-color: #ffe6e6; }
    ins { background-color: #e6ffe6; }
    sup.follow { color: #5555ff; }
</style>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
		<li><a href="{% url 'admin:index' %}"><i class="icon-home"></i></a> <span class="divider">/</span></li>{% if not ADMIN_DISABLE_APP_INDEX %}
		<li><a href="{% url 'admin:app_list' app_label %}">{{app_label|capfirst|escape}}</a> <span class="divider">/</span></li>{% endif %}
        <li><a href="{{changelist_url}}">{{opts.verbose_name_plural|capfirst}}</a><span class="divider">/</span></li>
        <li><a href="{{change_url}}">{{original|truncatewords:"18"}}</a>  <span class="divider">/</span></li>
        <li><a href="../">{% trans "History" %}</a><span class="divider">/</span></li>
        <li class="active">{% blocktrans with opts.verbose_name_plural|escape as name %}Compare {{name}}{% endblocktrans %}
        {{title}}</li>
    </ul>{% endblock %}

{% block content %}
    <div id="content-main">
        
        <h1 class="help">
            {% blocktrans with date1=version1.revision.date_created|date:_("DATETIME_FORMAT") date2=version2.revision.date_created|date:_("DATETIME_FORMAT") %}
                Compare <strong>{{ date1 }}</strong> with <strong>{{ date2 }}</strong>:
            {% endblocktrans %}
        </h1>
        
        <h2>&lsaquo; <a href="{{history_url}}">{% trans "Go back to history list" %}</a></h2>
        
        {% for field_diff in compare_data %}
        <div class="inline-related">
            <h3 class="light-blue-degrade"><b>{{ field_diff.field.verbose_name }}{% if field_diff.is_related and not field_diff.follow %}<sup class="follow"> <i class="icon-certificate"></i></sub>{% endif %}</b></h3>
            <div class="field">
            {% if field_diff.field.help_text %}<p class="help">{{ field_diff.field.help_text }}</p>{% endif %}
            <div class="module">
                <p>{{ field_diff.diff }}</p>
            </div>
            </div>
        </div>
        {% empty %}
            <div class="module">
                <p><strong>There are no differences.</strong></p>
            </div>
        {% endfor %}
        
        <h4>{% trans "Edit comment:" %}</h4>
        <blockquote>{{ version2.revision.comment|default:"(there exist not comment)" }}</blockquote>
        
        {% if has_unfollowed_fields %}
        <h4 class="follow">{% trans "Note:" %}</h4>
        <p class="follow">
            Fields/entries marked with <sup class="follow"> <i class="icon-certificate"></i></sup> are not under reversion control.
            It may be that not all marked information are correct.
        </p>
        {% endif %}

        <h2>&lsaquo; <a href="{{history_url}}">{% trans "Go back to history list" %}</a></h2>
    </div>
{% endblock %}

third_party/yawdadmin/templates/reversion-compare/object_history.html
{% extends "admin/object_history.html" %}
{% load i18n %}

{% block content %}
    <div id="content-main">
    
        <p>{% blocktrans %}Choose a date from the list below to revert to a previous version of this object.{% endblocktrans %}</p>
    
        <div class="module">
            {% if action_list %}
                {% if compare_view %}<form method="GET" action="../history/compare/">{% endif %}
					<table id="change-history" class="table table-bordered table-striped">
                    <thead>
						<tr class="grey-degrade">
                            {% if compare_view %}
                                <th scope="col">
                                    {% if comparable %}
                                        <input type="submit" value="{% trans 'compare' %}">
                                    {% else %}
                                       <i>{% trans 'compare' %}</i>
                                    {% endif %}
                                </th>
                            {% endif %}
                            <th scope="col">{% trans 'Date/time' %}</th>
                            <th scope="col">{% trans 'User' %}</th>
                            <th scope="col">{% trans 'Comment' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for action in action_list %}
                            <tr>
                                {% if compare_view %}
                                <td scope="row">
                                    {% if comparable %}
                                       <input type="radio" name="version_id1" value="{{ action.version.pk }}" {% if action.first %}style="visibility:hidden" {% endif %}{% if action.second %}checked="checked" {% endif %}/>
                                       <input type="radio" name="version_id2" value="{{ action.version.pk }}" {% if action.first == 1 %}checked="checked" {% endif %}/>
                                    {% else %}
                                       <i>-</i>
                                    {% endif %}
                                </td>
                                {% endif %}
                                <th scope="row"><a href="{{action.url}}">{{action.revision.date_created|date:_("DATETIME_FORMAT")}}</a></th>
                                <td>
                                    {% if action.revision.user %}
                                        {{action.revision.user.username}}
                                        {% if action.revision.user.first_name %} ({{action.revision.user.first_name}} {{action.revision.user.last_name}}){% endif %}
                                    {% endif %}
                                </td>
                                <td>{{action.revision.comment|default:""}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% if compare_view %}</form>{% endif %}
            {% else %}
                <div class="alert">{% trans "This object doesn't have a change history. It probably wasn't added via this admin site." %}</div>
            {% endif %}
        </div>
    </div>
{% endblock %}