help/urls.py
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import patterns, url

urlpatterns = patterns('help.views',
    url(r'^faqs/$', 'faqs', name='faqs'),
    url(r'^terms-and-conditions/$', 'terms', name='terms'),
    url(r'^about/$', 'about', name='about'),
)

main/urls.py
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'index', name='index'),
    url(r'^wall/$', 'wall', name='wall'),
    url(r'^live_search/$', 'live_search', name='live_search'),
    url(r'^box/leave/$', 'leave_box', name='leave_box'),
    url(r'^box/(?P<slug>[\w-]+)/$', 'box_detail', name='box_detail'),
)

third_party/django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

third_party/django_summernote/urls.py
from django.conf.urls import patterns, url
from django_summernote.views import editor, upload_attachment

urlpatterns = patterns(
    'django_summernote.views',
    url(r'^editor/(?P<id>.+)/$', editor,
        name='django_summernote-editor'),
    url(r'^upload_attachment/$', upload_attachment,
        name='django_summernote-upload_attachment'),
)

urls.py
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.conf.urls import patterns, url, include
from django.views.generic.base import TemplateView, RedirectView
from main.views import cached_javascript_catalog

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from yawdadmin import admin_site
admin_site._registry.update(admin.site._registry)


js_info_dict = {
    'packages': ('main',),
}

handler500 = 'djangotoolbox.errorviews.server_error'

urlpatterns = patterns('',
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),
    url(r'^jsi18n/$', cached_javascript_catalog, js_info_dict, name='cached_javascript_catalog'),
    (r'^i18n/', include('django.conf.urls.i18n')),


    url(r'^admin/', include(admin_site.urls)),

    url('', include('adminoauthlogin.urls', namespace='adminoauthlogin')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/',}, name='auth_logout_next'),
    (r'^summernote/', include('django_summernote.urls')),

    (r'^favicon\.ico$', RedirectView.as_view(url='/static/global/favicon.ico')),
    (r'^robots\.txt$', TemplateView.as_view(template_name='main/robots.txt', content_type='text/plain')),
    (r'^sitemap\.xml$', TemplateView.as_view(template_name='main/sitemap.xml', content_type='application/xml')),

    url('', include('main.urls', namespace='main')),
    url('invitations/', include('invitations.urls', namespace='invitations')),
    url('', include('help.urls', namespace='help')),
)

main/models.py
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from main.managers import PublishedBoxesManager
from uuslug import uuslug
from django.utils.translation import ugettext_lazy as _

class Box(models.Model):
    CODELAB = "codelab"
    TRACKSESSION = "tracksession"
    KEYNOTE = "keynote"
    WORKSHOP = "workshop"

    CONTENT_TYPE_CHOICES = (
                (CODELAB, _("CodeLab")),
                (TRACKSESSION, _("Track Session")),
                (KEYNOTE, _("Keynote")),
                (WORKSHOP, _("Workshop"))
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length = 80)
    image = models.FileField(upload_to='box_images')
    back_image = models.FileField(upload_to='box_back_images')
    type = models.CharField(max_length=15, choices=CONTENT_TYPE_CHOICES)
    description = models.TextField(max_length=1000)
    github_url = models.URLField(blank=True)
    drive_folder_url = models.URLField(blank=True)
    published = models.BooleanField(default=False)
    instructor = models.ForeignKey('main.Instructor')
    language = models.ForeignKey('main.Language')
    creator = models.ForeignKey(User, related_name="boxes", null=True, blank=True, on_delete=models.SET_NULL)

    objects = models.Manager()
    published_boxes = PublishedBoxesManager()

    class Meta:
        verbose_name_plural = "boxes"

    def __unicode__(self):
        return u"%s" % self.title

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.title, instance=self, max_length=80, word_boundary=True)
        super(Box, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('main:box_detail', args=[self.slug])

    def register_user(self, user):
        try:
            BoxRegistration.objects.get(user=user, box=self)
        except BoxRegistration.DoesNotExist:
            BoxRegistration.objects.create(user=user, box=self)

    def unregister_user(self, user):
        BoxRegistration.objects.filter(user=user, box=self).delete()

    def is_registered(self, user):
        try:
            BoxRegistration.objects.get(user=user.id,box=self)
            return True
        except BoxRegistration.DoesNotExist:
            return False

    def get_tags(self):
        tags = []
        box_tags = self.boxtag_set.all()
        for boxtag in box_tags:
            tags.append(boxtag.tag)
        return tags


class Unit(models.Model):
    title = models.CharField(max_length=300)
    video_link = models.URLField()
    order = models.IntegerField()
    box = models.ForeignKey(Box, related_name='units')

    def __unicode__(self):
        return u"%s - %s" % (self.box, self.video_link)

    class Meta:
        ordering = ['order']


class Tag(models.Model):
    title = models.CharField(max_length=50)
    icon = models.FileField(upload_to='tag_images')
    slug = models.SlugField(max_length = 40)
    description = models.TextField(max_length=500, blank=True)

    class Meta:
        ordering = ['title']

    def __unicode__(self):
        return u"%s" % self.title

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.title, instance=self, max_length=40, word_boundary=True)
        super(Tag, self).save(*args, **kwargs)


class Link(models.Model):
    title = models.CharField(max_length=50)
    url = models.URLField()
    box = models.ForeignKey(Box, related_name="links")

    def __unicode__(self):
        return u"%s" % self.title


class BoxTag(models.Model):
    box = models.ForeignKey(Box)
    tag = models.ForeignKey(Tag)

    def __unicode__(self):
        return u"%s - %s" % (self.box, self.tag)


class BoxRegistration(models.Model):
    box = models.ForeignKey(Box)
    user = models.ForeignKey(User)

    def __unicode__(self):
        return u"%s - %s" % (self.box, self.user)


class UserTag(models.Model):
    user = models.ForeignKey(User)
    tag = models.ForeignKey(Tag)

    def __unicode__(self):
        return u"%s - %s" % (self.user, self.tag)


class Instructor(models.Model):
    PLATFORM = "platform"
    ENGINEERING = "engineering"
    GDE = "gde"
    GDG = "gdg"
    TECHMAKERS = "techmakers"
    OTHERS = "others"

    AFFILIATION_CHOICES = (
                (PLATFORM, _("Google Developer Platform")),
                (ENGINEERING, _("Google Engineering")),
                (GDE, _("Google Developer Experts")),
                (GDG, _("Google Developers Groups")),
                (TECHMAKERS, _("Women Techmakers")),
                (OTHERS, _("Google Others"))
    )

    name = models.CharField(max_length=100)
    affiliation = models.CharField(max_length=15, choices=AFFILIATION_CHOICES)
    description = models.TextField(max_length=100)
    image = models.FileField(upload_to='instructor_images')
    plus_page_id = models.CharField(max_length=100, blank=True)

    def __unicode__(self):
        return u"%s" % self.name


class Language(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length = 80)
    short_name = models.CharField(max_length=300, blank=True)
    image = models.FileField(upload_to='language_images')

    def __unicode__(self):
        return u"%s" % self.name

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.name, instance=self, max_length=80, word_boundary=True)
        super(Language, self).save(*args, **kwargs)

main/views.py
# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from django.shortcuts import render_to_response, get_object_or_404
from django.template.context import RequestContext
from settings import JAVASCRIPT_TRANSLATION_VERSION
from main.models import Box, Tag, Language
from django.contrib.auth.decorators import login_required
from search.views import live_search_results
from main.forms import LiveSearchForm
from social.apps.django_app.default.models import UserSocialAuth
from oauth2client.client import OAuth2Credentials
from config.models import SiteConfiguration
import httplib2
from apiclient.discovery import build
from django_ajax.decorators import ajax
from django.views.decorators.http import require_POST
from django.views.decorators.cache import cache_page, never_cache
from django.views.i18n import javascript_catalog
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse


def index(request):

    extra_context = {}

    if request.user.is_staff:
        extra_context['boxes'] = Box.objects.select_related('boxtag_set').all()
    else:
        extra_context['boxes'] = Box.published_boxes.select_related('boxtag_set').all()

    extra_context['tags'] = Tag.objects.all()

    extra_context['hide_boxes_link'] = True

    extra_context['search_form'] = LiveSearchForm()

    return render_to_response('main/index.html',
                              extra_context,
                              context_instance=RequestContext(request))


@login_required
@never_cache
def wall(request):

    extra_context = {}

    extra_context['boxes'] = Box.published_boxes.my_boxes(request.user, request.user.is_staff)

    extra_context['hide_my_boxes_link'] = True

    extra_context['search_form'] = LiveSearchForm()

    return render_to_response('main/wall.html',
                              extra_context,
                              context_instance=RequestContext(request))


@login_required
def box_detail(request, slug):

    if request.user.is_staff:
        box = get_object_or_404(Box.objects.select_related('units', 'instructor', 'links'), slug=slug)
    else:
        box = get_object_or_404(Box.published_boxes.select_related('units', 'instructor', 'links'), slug=slug)

    box.register_user(request.user)

    extra_context = {}

    extra_context['box'] = box
    extra_context['box_tags'] = box.get_tags()

    extra_context['search_form'] = LiveSearchForm()

    files = []
    if box.drive_folder_url:
        config = SiteConfiguration.objects.get()

        access_token = UserSocialAuth.get_social_auth_for_user(request.user, provider='google-oauth2').get().tokens
        credentials = OAuth2Credentials(access_token, config.google_oauth2_key,
                                    config.google_oauth2_secret, None, None, None, None)

        # Create an httplib2.Http object and authorize it with our credentials
        http = httplib2.Http()
        http = credentials.authorize(http)

        drive_service = build('drive', 'v2', http=http)

        folder_id = box.drive_folder_url.split("/")[-1]
        page_token = None
        while True:
            try:
                param = {}
                if page_token:
                    param['pageToken'] = page_token
                folder_files = drive_service.files().list(q='\'%s\' in parents' % folder_id, **param).execute()

                files.extend(folder_files['items'])

                page_token = folder_files.get('nextPageToken')
                if not page_token:
                    break
            except:
                break

    extra_context['files'] = files

    return render_to_response('main/box_detail.html',
                              extra_context,
                              context_instance=RequestContext(request))


@ajax
@login_required
@require_POST
def leave_box(request):
    box_id = request.POST.get('box_id','')
    box = get_object_or_404(Box.published_boxes, id=box_id)

    box.unregister_user(request.user)

    redirect = request.POST.get('redirect',False)
    if redirect:
        return HttpResponseRedirect(reverse('main:wall'))

    return {'box_id': box.id}


def filter_published(request, results):
    languages = request.GET.get('languages',False)
    content_types = request.GET.get('content_types',False)
    if languages:
        results.filter(language_id=languages)
    if content_types:
        results.filter(type=content_types)
    return results.filter(published=True)

def live_search(request):
    return live_search_results(request, Box, 'autocomplete_index', limit=3,
        redirect=True, query_converter=filter_published,
        result_item_formatting=
            lambda box: {'value': u'<div>%s / <i>%s</i><img src="%s" class="float-right item-img" /></div>' % (box.title, box.instructor.name, box.language.image.url),
            'result': box.title, })


# The value returned by get_version() must change when translations change.
@cache_page(86400, key_prefix='js18n-%s' % JAVASCRIPT_TRANSLATION_VERSION)
def cached_javascript_catalog(request, domain='djangojs', packages=None):
    return javascript_catalog(request, domain, packages)

main/templates/main/box_detail.html
<!--Copyright 2015 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.-->

{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}
{% load url from future %}
{% load youtube_embed %}
{% load youtube_thumbnail %}

{% block title %} - {{ box.title }}{% endblock %}

{% block body_css_class %}box-detail{% endblock %}

{% block content %}

	<div id="content" class="row">

		{% if not box.published %}
			<div id="not-published" class="c15-15 cols offset-3-15">
				<p>{% trans "Box not published yet. The admin must approve it." %}</p>
			</div>
		{% endif %}

		<div class="header-title-detail show-tablet show-mobile hidden offset-3-15">
			<div class="table-block">
				<a class="back-button c2-15 tablet-c2-15 mobile-c3-15 cols" href="{% url 'main:index' %}">
					<i class="ficon fa-angle-left"></i>
					<span class="hidden show-inline-mobile white-text">{% trans "Back" %}</span>
				</a>
				<h1 class="title c13-15 tablet-c13-15 mobile-c12-15 cols" title="{{ box.title }}">{{ box.title }}</h1>
			</div>
		</div>

		<div id="detail-side-nav" class="side-nav c3-15 md-c15-15 tablet-c15-15 cols">

			<div class="scrolleable-area row">
				<div class="header-title-detail hide-tablet hide-mobile">
					<div class="table-block">
						<a class="back-button c2-15 tablet-c2-15 cols" href="{% url 'main:index' %}">
							<i class="ficon fa-angle-left"></i>
							<span class="hidden show-inline-mobile white-text">{% trans "Back" %}</span>
						</a>
						<h1 class="title c13-15 tablet-c13-15 cols" title="{{ box.title }}">{{ box.title }}</h1>
					</div>
				</div>

				<div class="description c15-15 cols">
					<h3 class="small title">{% trans "Synopsis" %}</h3>
					<p>{{ box.description }}</p>
				</div>

				{% if box.github_url or box.drive_folder_url %}
					{% if box.github_url %}
						<div class="button-area c15-15 cols">
							<a class="button blue social-button github" href="{{ box.github_url }}" title="{% trans "View sourcecode in Github" %}" target="_blank">
								<i class="ficon medium fa-github-alt"></i>
								<span class="text">{% trans "View sourcecode" %}</span>
							</a>
						</div>
					{% endif %}
					{% if box.drive_folder_url %}
						<div class="button-area c15-15 cols">
							<a class="button blue social-button drive" href="{{ box.drive_folder_url }}" title="{% trans "View files in drive" %}" target="_blank">
								<i class="ficon medium fa-file-o"></i>
								<span class="text">{% trans "View files in drive" %}</span>
							</a>
						</div>
						{% if files %}
							<div id="box-files">
								<div class="c15-15 cols">
									<h3 class="small title">{% trans "Files" %}</h3>
								</div>
								<table class="table-gray">
									<tbody>
										{% for file in files %}
											<tr>
												<td width="15%"><img class="file-icon a-center" src="{{ file.iconLink }}"></td>
												<td width="85%"><a class="" href="{{ file.alternateLink }}" target="_blank"><strong>{{ file.title }}</strong></a></td>
											</tr>
										{% endfor %}
									</tbody>
								</table>
							</div>
						{% endif %}
					{% endif %}
				{% endif %}

				<div class="call-to-action c15-15 cols hide-tablet hide-mobile">
					<small><a href="#" class="red-text" onclick="leave_box('{{ box.id }}')">{% trans "Leave Box" %}</a></small>
				</div>

			</div>
		</div>

		<!--
		{% include "main/toggle-side-nav.html" %}
		-->

		<div id="detail" class="c12-15 offset-3-15 md-c15-15 tablet-c15-15 cols">
			<div id="bdk-slider" class="row blueimp-gallery blueimp-gallery-controls blueimp-gallery-carousel">
				<div class="slides"></div>
				<h3 class="title"></h3>
				<div class="prev slider-arrow slider-left"><i class="ficon arrow fa-angle-left"></i></div>
				<div class="next slider-arrow slider-right"><i class="ficon arrow fa-angle-right"></i></div>
				<ol class="indicator"></ol>
			</div>

			<div id="instructor" class="row">
				<div class="info c15-15 cols">
					<aside class="instructor-profile">
						<img class="pic" src="{{ box.instructor.image.url }}" />
						<h4 class="name title">{{ box.instructor.name }}</h4>
						<div class="summary">{{ box.instructor.get_affiliation_display }}</div>
					</aside>
					<article class="instructor-content c10-15 cols">
						<header class="tags hide-tablet">
							{% for tag in box_tags %}
								<div class="tag">
									<img src="{{ tag.icon.url }}" class="tag-img" title="{{ tag.title }}" alt="{{ tag.title }}">
									<div class="tag-title">{{ tag.title }}</div>
								</div>
							{% endfor %}
						</header>
						<p>{{ box.instructor.description }}</p>
						<ul class="instructor-links horz list">
							{% for link in box.links.all %}
								<li class="item"><a href="{{ link.url }}" target="_blank">{{ link.title }}</a></li>
							{% endfor %}
						</ul>
					</article>
				</div>

				<div class="call-to-action c15-15 center-text cols hidden show-mobile show-tablet">
					<div class="row row-two">
						<a href="#" class="red-text button inline-block clear" onclick="leave_box('{{ box.id }}')">{% trans "Leave Box" %}</a>
					</div>
				</div>
			</div>

			<!--
			<div class="stats hide-tablet hide-mobile">
				{% include "main/footer.html" %}
			</div>
			-->
		</div>

	</div>

{% endblock %}


{% block js %}
	<script src="{% static 'vendor/blueimp/blueimp-helper.js' %}"></script>
	<script src="{% static 'vendor/blueimp/blueimp-gallery.js' %}"></script>
	<script src="{% static 'vendor/blueimp/blueimp-gallery-fullscreen.js' %}"></script>
	<script src="{% static 'vendor/blueimp/blueimp-gallery-indicator.js' %}"></script>
	<script src="{% static 'vendor/blueimp/blueimp-gallery-video.js' %}"></script>
	<script src="{% static 'vendor/blueimp/blueimp-gallery-youtube.js' %}"></script>
	<script>
		$(function () {
			blueimp.Gallery([
				{% for unit in box.units.all %}
					{
						title: '{{ unit.title }}',
						type: 'text/html',
						youtube: '{{ unit.video_link|youtube_get_id }}',
						thumbnail: '{{ unit.video_link|youtube_thumbnail_url }}'
					}{% if not forloop.last %},{% endif %}
				{% endfor %}
			], {
				container: '#bdk-slider',
				carousel: true,
				startSlideshow: false
			});
		});
		function leave_box(id) {
            ajaxPost(
                '/box/leave/',
                {'box_id': id, 'redirect': true},
                function(response) {

                },
                {
                    'onError': function(response){
                        alert('There was an error. Please try again.');
                    }
                }
            );
        }
	</script>
{% endblock %}

main/templates/main/drive_files.html
<!--Copyright 2015 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.-->

<div id="box-files" class="c15-15 cols">
	<h2 class="title">{% trans "Files" %}</h2>
	<hr>
	<table class="table-gray">
		<thead>
			<th></th>
			<th>Title</th>
			<th>Date</th>
			<th></th>
		</thead>
		<tbody>
			{% for i in 'xxx'  %}
				<tr>
					<td><i class="ficon rounded fa-folder"></i></td>
					<td><strong>File name</strong></td>
					<td>14/08/14</td>
					<td><i class="ficon fa-ellipsis-v"></i></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

main/templates/main/footer.html
<!--Copyright 2015 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.-->

{% load i18n %}
{% load url from future %}

<footer class="c15-15 cols center-text">
	<a class="button link inline-block" href="{% url 'help:about' %}">{% trans "About" %}</a>
	<a class="button link inline-block" href="{% url 'help:faqs' %}">{% trans "FAQ" %}</a>
	<a class="button link inline-block" href="{% url 'help:terms' %}">{% trans "Terms & Conditions" %}</a>
</footer>

main/templates/main/toggle-side-nav.html
<!--Copyright 2015 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.-->

<div id="toggle-side-nav" class="c12-15 offset-3-15 cols tablet-c15-15 hidden hide-tablet show-mobile center-text" onclick="$('body').toggleClass('show-filters');">
	<i class="ficon fa-chevron-down"></i>
</div>

main/templates/main/wall.html
<!--Copyright 2015 Google Inc. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.-->

{% extends 'base.html' %}

{% load i18n %}
{% load staticfiles %}

{% block title %} - {% trans "My wall" %}{% endblock %}

{% block content %}

	<div id="content" class="wall row">

		<div class="header-title c15-15 cols">
			<div class="inner-header row">
				<h1 class="title">{% trans "My Boxes" %}</h1>
				<div class="summary">{% trans "These are the boxes you are registered in" %}</div>
			</div>
		</div>

		<ul id="my-boxes" class="boxes c15-15 cols">
		    {% with registered=True unsuscribe=True %}
				{% for box in boxes %}
					{% include "main/box_thumb.html" %}
				{% empty %}
					<div class="center-box center-text">
						<div class="row row-one">
							<h2 class="message">{% trans "You haven't joined any box yet" %}</h2>
						</div>
						<div class="row row-two">
							<a class="button green medium inline-block" href="{% url 'main:index' %}">{% trans "Try any box you like!" %}</a>
						</div>
					</div>
				{% endfor %}
		    {% endwith %}
		</ul>
		<!-- 
		<div class="stats hide-mobile hide-tablet">
			{% include "main/footer.html" %}
		</div> 
		-->

	</div>

{% endblock %}

{% block js %}
    <script src="{% static 'main/js/box_preview.js' %}"></script>
{% endblock %}